server:
  port:
    8090

# nacos 服务注册配置
spring:
  application:
    name: order-openfeigh-service  #nacos 服务名称
  cloud:
    nacos:
      server-addr: 127.0.0.1:8847 #nacos 服务其地址
      discovery:
        username: nacos
        password: nacos
        namespace: public
        ip: 127.0.0.1
#logging:
#  level:
#    com.tulingxueyuan.order.feign:debug
#sentinel:
#  transport:
#    dashboard: 127.0.0.1:5080
#  web-context-unify: false  #解决链路树问题，默认为true时没有维护链路树
feign:
  sentinel:
    enabled: true  #feign 整合sentinel
