server:
  port:
    8070

# nacos 服务注册配置
spring:
  application:
    name: order-ribbon-sentinel-service  #nacos 服务名称
  cloud:
    nacos:
      server-addr: 127.0.0.1:8847 #nacos 服务其地址
      discovery:
        username: nacos
        password: nacos
        namespace: public
        ip: 127.0.0.1
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858
      web-context-unify: false  #解决链路树问题，默认为true时没有维护链路树
      datasource:
        flow-rule:   #可以自定义
          nacos:
            servver-addr : 127.0.0.1:8847
            username: nacos
            password: nacos
            dataId: order-sentinel-flow-rule    #对应nacos中的配置dataId
            rule-type: flow

#stock-service:
#  ribbon:
#    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
#ribbon:
#  eager-load:
#    enabled: true
#    clients: stock-service