server:
  port:
    9110

# nacos 服务注册配置
spring:
  application:
    name: order-ribbon-nacos-sentinel-sky-seata-service  #nacos 服务名称
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848 #nacos 服务其地址
      discovery:
        username: nacos
        password: nacos
        namespace: public
        ip: 127.0.0.1

    #sentinel 配置
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858
      web-context-unify: false  #解决链路树问题，默认为true时没有维护链路树
      datasource:
        sentinel-datasource-nacos-flowrule:   #可以自定义
          nacos:
            servver-addr : 127.0.0.1:8848
            username: nacos
            password: nacos
            dataId: order-sentinel-flow-rule    #对应nacos中的配置dataId
            groupId: DEFAULT_GROUP
            rule-type: flow
            data-type: json
#        flow:
#          nacos:
#            server-addr: 127.0.0.1:8848
#            dataId: ${spring.application.name}-flow-rules
#            groupId: SENTINEL_GROUP
#            rule-type: flow
#        degrade:
#          nacos:
#            server-addr: 127.0.0.1:8848
#            dataId: ${spring.application.name}-degrade-rules
#            groupId: SENTINEL_GROUP
#            rule-type: degrade
#        system:
#          nacos:
#            server-addr: 127.0.0.1:8848
#            dataId: ${spring.application.name}-system-rules
#            groupId: SENTINEL_GROUP
#            rule-type: system
#        authority:
#          nacos:
#            server-addr: 127.0.0.1:8848
#            dataId: ${spring.application.name}-authority-rules
#            groupId: SENTINEL_GROUP
#            rule-type: authority
#        param-flow:
#          nacos:
#            server-addr: 127.0.0.1:8848
#            dataId: ${spring.application.name}-param-flow-rules
#            groupId: SENTINEL_GROUP
#            rule-type: param-flow


    alibaba:
      seata:
        tx-service-group: guangzhou  #对应seata服务端配置要一致

  #druid+mysql数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_mybatis?charaterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 'root'
#    #数据源其他配置
#    validationQuery: SELECT 1 from dual
#    pool-prepared-statements: true
#
#    filters: swat,wall
#    maxPoolPrepareStatementPerConnectionSize: 20
#    useGlobalDataSourceStat: true
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

    schema: classpath:sql/schema.sql
    druid:
      stat-view-servlet:
        enabled: true    #启动数据库连接池等相关监控
        allow: 127.0.0.1
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      web-stat-filter:
        enabled: true   #启动访问监控过滤
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

#  springboot admin client to server hostport
  boot:
    admin:
      client:
        url: http://127.0.0.1:7001
        instance:
          prefer-ip: true  #基于ip地址向服务器注册，默认域名注册
#    initialization-mode: always

#actuator 配置生效
management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true  #开启所有监控点
  endpoint:
    health:
      show-details: always
      enabled: true
    info:
      enabled: false
    metrics:
      enabled: true


#设置mybatis
mybatis:
  mapper-locations: classpath:com/tulingxueyuan/order/mapper/*Mapper.xml
  type-aliases-package: com.tulingxueyuan.mybatis.entity

#stock-service:
#  ribbon:
#    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
#ribbon:
#  eager-load:
#    enabled: true
#    clients: stock-service

#feign 对sentinel的支持
feign:
  sentinel:
    enabled: true

#rocketmq配置
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: my-producer-group-test



