server:
  port:
    8040

# nacos 服务注册配置
spring:
  application:
    name: order-ribbon-service  #nacos 服务名称
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848 #nacos 服务其地址
      discovery:
        username: nacos
        password: nacos
        namespace: public
        ip: 127.0.0.1
stock-service:
  ribbon:
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
ribbon:
  eager-load:
    enabled: true
    clients: stock-service