server:
  port:
    9000
spring:
  application:
    name: pringboot-order-mybatis-seata
  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_mybatis?charaterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 'root'
    #数据源其他配置
    validationQuery: SELECT 1 from dual
    poolPrepareStatements: true

    filters: swat,wall
    maxPoolPrepareStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

    schema: classpath:sql/schema.sql
    druid:
      stat-view-servlet:
        enabled: true    #启动数据库连接池等相关监控
        allow: 127.0.0.1
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      web-stat-filter:
        enabled: true   #启动访问监控过滤
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
#    initialization-mode: always

#设置mybatis
mybatis:
  mapper-locations: classpath:com/tulingxueyuan/mapper/*Mapper.xml
  type-aliases-package: com.tulingxueyuan.mybatis.entity






