server:
  port:
    7020

# nacos 服务注册配置
spring:
  application:
    name: order-loadbalancer-service  #nacos 服务名称
  cloud:
    nacos:
      server-addr: 127.0.0.1:8847 #nacos 服务其地址
      discovery:
        username: nacos
        password: nacos
        namespace: public
        ip: 127.0.0.1

    loadbalancer:
      ribbon:
        enabled: false




