server:
  port:
    8050

# nacos 服务注册配置
spring:
  application:
    name: order-openfeigh-service  #nacos 服务名称
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848 #nacos 服务其地址
      discovery:
        username: nacos
        password: nacos
        namespace: public
        ip: 127.0.0.1

#    loadbalancer:
#      ribbon:
#        enabled: false
##logging:
##  level:
##    com.tulingxueyuan.order.feign:debug
#feign:
#  client:
#    config:
#      stock-service:
#        loggerlevel:BASIC
#        connectTimeout:5000
#        readTimeout:3000



